apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llmops-prod

namePrefix: prod-
nameSuffix: ""

resources:
  - ../../base

patches:
  - target:
      kind: InferenceService
      name: qwen25-05b-instruct
    patch: |-
      - op: replace
        path: /metadata/annotations/openshift.io~1display-name
        value: "qwen2.5-0.5b-production"
      - op: add
        path: /spec/predictor/canaryTrafficPercent
        value: 100
      - op: replace
        path: /spec/predictor/model/runtime
        value: "prod-qwen25-05b-instruct"
      - op: replace
        path: /spec/predictor/minReplicas
        value: 2
      - op: replace
        path: /spec/predictor/maxReplicas
        value: 3
      - op: replace
        path: /spec/predictor/model/resources/limits/cpu
        value: "4"
      - op: replace
        path: /spec/predictor/model/resources/limits/memory
        value: "12Gi"
      - op: replace
        path: /spec/predictor/model/resources/requests/cpu
        value: "2"
      - op: replace
        path: /spec/predictor/model/resources/requests/memory
        value: "8Gi"

