apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llmops-staging

namePrefix: staging-
nameSuffix: ""

resources:
  - ../../base

patches:
  - target:
      kind: InferenceService
      name: qwen25-05b-instruct
    patch: |-
      - op: replace
        path: /metadata/annotations/openshift.io~1display-name
        value: "qwen2.5-0.5b-staging-v3"
      - op: add
        path: /metadata/annotations/serving.knative.dev~1revision-history-limit
        value: "3"
      - op: add
        path: /spec/predictor/canaryTrafficPercent
        value: 100
      - op: replace
        path: /spec/predictor/model/runtime
        value: "staging-qwen25-05b-instruct"
      - op: replace
        path: /spec/predictor/minReplicas
        value: 1
      - op: replace
        path: /spec/predictor/maxReplicas
        value: 2
      - op: replace
        path: /spec/predictor/model/resources/limits/cpu
        value: "3"
      - op: replace
        path: /spec/predictor/model/resources/limits/memory
        value: "8Gi"
      - op: replace
        path: /spec/predictor/model/resources/requests/cpu
        value: "1"
      - op: replace
        path: /spec/predictor/model/resources/requests/memory
        value: "6Gi"

